testenv: test
driver: macaca
desiredcaps:
    - platformName : Android
      udid: 'MQS7N19403034696'
      # Android
      restart: true
      clear: true
      package: com.taobao.taobao
      activity: com.taobao.tao.TBMainActivity
      automationName: Appium
      noReset: True
      # iOS
      bundleId: com.apple.mobilesafari
      reuse: 3

testcase:
    - testcase/OpenWebView.yaml
