testenv: test
driver: macaca
desiredcaps:
    - platformName : 'iOS'
      udid: '7865cebc58f19e8f993bff9f2928b28557f37ff4'
      # Android
      restart: true
      clear: true
      package: com.taobao.taobao
      activity: com.taobao.tao.TBMainActivity
      automationName: Appium
      noReset: True
      # iOS
      bundleId: com.apple.mobilesafari
      reuse: 3

testcase:
    - testcase/OpenTaobao.yaml
    - testcase/OpenGithub.yaml
