testenv: test  # 测试环境
# 初始化参数
desiredcaps:
    - platformName : iOS # 平台
      udid: 5084DAF0-56C5-4279-B726-0C1B87E12165 # 设备id
      # Android
      restart: false
      package: com.taobao.taobao
      activity: com.taobao.taobao/com.taobao.tao.TBMainActivity
      # iOS
      bundleId: com.apple.mobilesafari
# case
testcase:
    - testcase/OpenWebView.yaml